# Generated by Django 4.2.11 on 2025-03-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
    ]
