# Generated by Django 4.2.11 on 2025-04-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_rename_created_at_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
