# Generated by Django 4.2.11 on 2025-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_booking_stripe_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
