# Generated by Django 4.2.11 on 2025-05-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_alter_ticket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='booking_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
