# Generated by Django 4.2.11 on 2025-05-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_rename_id_booking_booking_id_ticket_pdf_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='id',
        ),
    ]
