# Generated by Django 4.2.11 on 2025-05-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_rename_booking_id_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
