# Generated by Django 4.2.11 on 2025-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_remove_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='verify_code',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
