# Generated by Django 4.2.11 on 2025-03-24 00:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Animation', 'Animation'), ('Sports', 'Sports')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('release_date', models.DateField()),
                ('imdb_rating', models.FloatField()),
                ('description', models.TextField()),
                ('actors', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_recent', models.BooleanField(default=False)),
                ('trailer_url', models.URLField()),
                ('seats_available', models.PositiveIntegerField()),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies_genre', to='Movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime_cinemahall', to='Movies.cinemahall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_showtime', to='Movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='movie',
            field=models.ManyToManyField(related_name='movie_cinema_hall', to='Movies.movie'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemahall_showtime', to='Movies.showtime'),
        ),
    ]
