# Generated by Django 4.2.11 on 2025-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Animation', 'Animation'), ('Sports', 'Sports')], max_length=255),
        ),
    ]
