# Generated by Django 4.2.11 on 2025-04-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_remove_movie_is_recent_remove_movie_views_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(null=True),
        ),
    ]
