# Generated by Django 4.2.11 on 2025-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_alter_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.AddField(
            model_name='genre',
            name='type_id',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
