# Generated by Django 4.2.11 on 2025-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_remove_movie_runtime_genre_type_id_alter_genre_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='type_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
