# Generated by Django 4.2.11 on 2025-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0013_alter_genre_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_reviews',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
