# Generated by Django 4.2.11 on 2025-04-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0014_movie_movie_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_reviews',
        ),
    ]
