# Generated by Django 4.2.11 on 2025-04-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0016_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='cinemahall',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='cinemahall',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='time',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='location',
            field=models.CharField(default='Cinema_Hall No.1', max_length=255),
        ),
        migrations.AddField(
            model_name='showtime',
            name='starts_at',
            field=models.DateTimeField(default='2025-10-01 00:00:00'),
        ),
    ]
