# Generated by Django 4.2.11 on 2025-05-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0017_remove_cinemahall_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(default='Cinema Hall', max_length=50),
        ),
    ]
