# Generated by Django 4.2.11 on 2025-05-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0018_alter_cinemahall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
