# Generated by Django 4.2.11 on 2025-03-24 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_input', to=settings.AUTH_USER_MODEL),
        ),
    ]
