# Generated by Django 4.2.11 on 2025-03-24 00:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_transaction_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('booking_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.booking')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_payment', to='Bookings.ticket')),
            ],
        ),
    ]
