# Generated by Django 4.2.11 on 2025-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booked_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
